name: QRohlf.com
description: A blog about startups, technology, and other interesting things.
url: http://qrohlf.com
permalink: /posts/:title
markdown: redcarpet
future: true
poole:
    word_separator: "-"
include: [".well-known"]
