description: A blog about startups, technology, and other interesting things.
url: http://qrohlf.com
permalink: /posts/:title
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
future: true
poole:
    word_separator: "-"
include: [".well-known"]
sass:
    sass_dir: _sass
    sourcemap: true